1 homework
Wandegor/tl_practice_2024 pull request #1
Opened 2024-07-02 17:56 UTC by wander122156

2024-07-04 10:18 UTC, VladTL commented
1. У тебя очень много ненужных файлов в проекте (папка .vs, obj), они не должны попадать в гит. 
Тебе нужно добавить .gitignore файл в проект, можно сразу положить в корень репозитория.
2. Также в требованиях к домашке было использовать .editorconfig файл

2024-07-04 10:23 UTC, VladTL requested changes

2024-07-04 10:23 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +﻿AddNewProduct();
Смущает большое количество функций в Program.cs, к тому же он используется без явного Program класса. 
В целом такой подход (top-level statements) нормальный, но когда кода в нем становится сильно много - не очень.

Варианта предлагаю два (на твой выбор)
а.  
```
...
internal class Program
{
    public static void Main(string[] args)
    {
        AddNewProduct();

        string product = ReadInput("Название товара: ");
        int count = ReadProductQuantity();
        string name = ReadInput("Имя пользователя: ");
        string address = ReadInput("Адрес доставки: ");
        
        ConfirmNewProduct(product, count, name, address);
    }   

    ... остальные функции
}
```

Сделать что-то типа такого. 

б. Либо оставить top-level statements но всю логику вынести в другой класс и файл. 

Можешь ознакомиться https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/top-level-statements

2024-07-04 10:23 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +        Console.WriteLine( "Quantity invalid" );
Все тексты на русском а этот на английском, давай все приведем к одному виду (на русском, например)

2024-07-04 10:23 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +        address = Console.ReadLine();
Console.ReadLine() возвращает nullable тип

2024-07-04 11:42 UTC, wander122156 commented on OrderManager/OrderManager/Program.cs
> +﻿AddNewProduct();
Всё, увидел, постараюсь исправить.

2024-07-04 16:11 UTC, VladTL commented on OrderManager/OrderManager/OrderManager.csproj
> +    <Nullable>enable</Nullable>
Поставь здесь     
<Nullable>disable</Nullable>

Если вкратце, в одной из последних версий C# добавили nullable reference types и если эта настройка стоит, то тебе надо явно все экземпляры классов помечать как "?"
Например:
 string**?** userName = Console.ReadLine();

Договорились с ребятами, что вам пока не нужно об этом заморачиваться поэтому просто выключи эту настройку в проекте.

2024-07-10 13:00 UTC, VladTL requested changes

2024-07-10 13:00 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +            if ( confirmation == "да" )
давай case insensitive

2024-07-10 13:02 UTC, VladTL commented
Еще советую .editorconfig положить рядом с .gitignore в самую верхнюю директорию, чтобы не надо было в каждом проекте его добавлять

2024-08-11 13:08 UTC, merged